version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для веб-интерфейса RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
